# Generated by Django 3.2.12 on 2024-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(default=True, max_length=15, unique=True)),
                ('entity', models.CharField(choices=[('enterprise', 'Enterprise'), ('Government', 'Government')], max_length=50)),
                ('details', models.TextField()),
                ('reported_data', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=15)),
            ],
        ),
    ]
